<#assign ABANDONED_VEHICLE_COMPLAINT = "Abandoned Vehicle Complaint"/>
<#assign GARBAGE_CART = "Garbage Cart Black Maintenance/Replacement"/>
<#assign RODENT_BAITING = "Rodent Baiting/Rat Complaint"/>
<#assign POT_HOLE = "Pot Hole in Street"/>
<#assign GRAFFITI_REMOVAL = "Graffiti Removal"/>
<#assign TREE_DEBRIS = "Tree Debris"/>
<#assign TREE_TRIMS = "Tree Trim"/>
<#assign SANITATION_CODE_COMPLAINT = "Sanitation Code Violation"/>
<#assign VACANT_AND_ABANDONED_BUILDING = "Vacant/Abandoned Building"/>
